USE [master]
GO

/****** Object:  Database [TaskBoardDb]    Script Date: 21.05.2024 4:35:32 ******/
CREATE DATABASE [TaskBoardDb] ON  PRIMARY 
( NAME = N'TaskBoardDb', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TaskBoardDb.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TaskBoardDb_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\TaskBoardDb_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskBoardDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskBoardDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskBoardDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskBoardDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskBoardDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskBoardDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskBoardDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TaskBoardDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskBoardDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskBoardDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskBoardDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskBoardDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskBoardDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskBoardDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskBoardDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskBoardDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TaskBoardDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskBoardDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskBoardDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskBoardDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskBoardDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskBoardDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TaskBoardDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskBoardDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaskBoardDb] SET  MULTI_USER 
GO

ALTER DATABASE [TaskBoardDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskBoardDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskBoardDb] SET  READ_WRITE 
GO

